// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using loadMaxmind.Model;

namespace loadMaxmind.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20200209124822_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("loadMaxmind.Model.CountryLocation", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContinentCode")
                        .HasColumnType("text");

                    b.Property<string>("ContinentName")
                        .HasColumnType("text");

                    b.Property<string>("CountryIsoCode")
                        .HasColumnType("text");

                    b.Property<string>("CountryName")
                        .HasColumnType("text");

                    b.Property<string>("GeonameId")
                        .HasColumnType("text");

                    b.Property<string>("IsInEuropeanUnion")
                        .HasColumnType("text");

                    b.Property<string>("LocaleCode")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("CountryLocations");
                });

            modelBuilder.Entity("loadMaxmind.Model.Ipv4bloc", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("GeonameId")
                        .HasColumnType("text");

                    b.Property<long>("IpMax")
                        .HasColumnType("bigint");

                    b.Property<long>("IpMin")
                        .HasColumnType("bigint");

                    b.Property<string>("IsAnonymousProxy")
                        .HasColumnType("text");

                    b.Property<string>("IsSatelliteProvider")
                        .HasColumnType("text");

                    b.Property<string>("Network")
                        .HasColumnType("text");

                    b.Property<string>("RegisteredCountryGeonameId")
                        .HasColumnType("text");

                    b.Property<string>("RepresentedCountryGeonameId")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Ipv4bloc");
                });
#pragma warning restore 612, 618
        }
    }
}
