version: '3.9'

services:
  postgres:
    container_name: postgresql_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgresql}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgresql}
    volumes:
       - postgres:/data/postgres
       - ./data:/home
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
    postgres: